# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trippy_MVCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Trippy_MVCExample
  
  pod 'Blurberry'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'MapViewPlus'
  pod 'ReachabilitySwift'
  pod 'SDWebImage'
  
  target 'Trippy_MVCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
